---

- hosts: 127.0.0.1
  connection: local

  vars:
    dev_env_dir: /usr/local/dev-env

  tasks:
    - name: Check sudo Password
      ansible.builtin.command: whoami
      become: true
      changed_when: false

    - name: Create resolver directory
      ansible.builtin.file:
        path: /etc/resolver
        state: directory
        mode: "755"
      become: true

    - name: Symlink .test resolver file at /etc/resolver/test
      ansible.builtin.file:
        src: "{{ dev_env_dir }}/ansible/resolver-test.conf"
        dest: /etc/resolver/test
        state: link
        force: true
      become: true

    - name: Restart mDNSResponder
      ansible.builtin.command: killall -HUP mDNSResponder
      become: true
      changed_when: true
      failed_when: false

    - name: Kill any running mDNSResponderHelper processes
      ansible.builtin.command: killall mDNSResponderHelper
      become: true
      changed_when: true
      failed_when: false

    - name: Flush the DNS cache
      ansible.builtin.command: dscacheutil -flushcache
      become: true
      changed_when: true
      failed_when: false

    - name: Symlink dev script in /usr/local/bin
      ansible.builtin.file:
        src: "{{ dev_env_dir }}/bin/dev"
        dest: /usr/local/bin/dev
        state: link
        force: true
      become: true
